train: /content/drive/MyDrive/data/2020-02-cctv_highway/bbox/train
val: /content/drive/MyDrive/data/2020-02-cctv_highway/bbox/train

# number of classes
nc: 3

# class names
names: ['car', 'bus', 'truck']